language: python

python: 3.8
matrix:
    include:
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
        - python: "3.8"
          env: TOXENV=py38
        - python: "3.8"
          env: TOXENV=pep8
        - python: "3.8"
          env: TOXENV=coverage
install:
    - pip install tox
    - if [ "$TOXENV" = 'coverage' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'coverage' ]; then coveralls; fi
deploy:
    provider: pypi
    user: seantis
    password:
        secure: i+DqFD2GtsosNTuK1ryfVIXm+Ysani9zm66YeaOD8O0788+9kuWqTMJbSAgNF8fwrUW2Qn2ZXTNF/UU9SC+L93upbog1rhDmfcdkV9Tybn7hzeJzA7LXvNgGFN4p/KT3P4IbAfGzIV2N8KRZ7qmSqWCdUvlYLde9JriU3efy9Jg=
    distributions: "sdist bdist_wheel"
    on:
        tags: true
        condition: $TOXENV = py38
